services:
    oro_shopping_list.event_listener.shopping_list_total_listener:
        class: 'Oro\Bundle\ShoppingListBundle\EventListener\ShoppingListTotalListener'
        public: true
        arguments:
            - '@doctrine'
            - '@oro_config.global'
        tags:
            - { name: kernel.event_listener, event: oro_pricing.combined_price_list.update, method: onPriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.customer.combined_price_list.update, method: onCustomerPriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.customer_group.combined_price_list.update, method: onCustomerGroupPriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.website.combined_price_list.update, method: onWebsitePriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.config.combined_price_list.update, method: onConfigPriceListUpdate }

    oro_shopping_list.event_listener.line_item_preloading:
        parent: oro_entity.event_listener.default_preloading
        tags:
            - { name: kernel.event_listener, event: oro_entity.preload_entity.lineitem, method: onPreload }

    oro_shopping_list.migration.demo_data_fixtures_listener.shopping_list_totals:
        class: 'Oro\Bundle\ShoppingListBundle\EventListener\ShoppingListTotalsDemoDataFixturesListener'
        arguments:
            - '@doctrine'
            - '@oro_shopping_list.manager.shopping_list_total'
        tags:
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.post_load, method: onPostLoad }

    oro_shopping_list.event_listener.line_item_data_build_preload:
        class: Oro\Bundle\ShoppingListBundle\EventListener\LineItemDataBuildPreloadListener
        arguments:
            - '@oro_entity.manager.preloading_manager'
        tags:
            # This listener must be called first as it preloads line items data which might be needed by others.
            - { name: kernel.event_listener, event: oro_shopping_list.line_item.data_build, method: onLineItemData, priority: 1024 }

    oro_shopping_list.event_listener.line_item_data_build_edit:
        class: Oro\Bundle\ShoppingListBundle\EventListener\LineItemDataBuildEditListener
        arguments:
            - '@router'
            - '@oro_shopping_list.provider.product_units_list_provider'
        tags:
            - { name: kernel.event_listener, event: oro_shopping_list.line_item.data_build, method: onLineItemData }

    oro_shopping_list.event_listener.line_item_data_build_violations:
        class: Oro\Bundle\ShoppingListBundle\EventListener\LineItemDataBuildViolationsListener
        arguments:
            - '@oro_shopping_list.validator_service.line_item'
        tags:
            - { name: kernel.event_listener, event: oro_shopping_list.line_item.data_build, method: onLineItemData }
