services:
    oro_shopping_list.event_listener.shopping_list_total_listener:
        class: 'Oro\Bundle\ShoppingListBundle\EventListener\ShoppingListTotalListener'
        public: true
        arguments:
            - '@doctrine'
            - '@oro_config.global'
        tags:
            - { name: kernel.event_listener, event: oro_pricing.combined_price_list.update, method: onPriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.customer.combined_price_list.update, method: onCustomerPriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.customer_group.combined_price_list.update, method: onCustomerGroupPriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.website.combined_price_list.update, method: onWebsitePriceListUpdate }
            - { name: kernel.event_listener, event: oro_pricing.config.combined_price_list.update, method: onConfigPriceListUpdate }

    oro_shopping_list.event_listener.line_item_preloading:
        parent: oro_entity.event_listener.default_preloading
        tags:
            - { name: kernel.event_listener, event: oro_entity.preload_entity.lineitem, method: onPreload }

    oro_shopping_list.migration.demo_data_fixtures_listener.shopping_list_totals:
        class: 'Oro\Bundle\ShoppingListBundle\EventListener\ShoppingListTotalsDemoDataFixturesListener'
        arguments:
            - '@doctrine'
            - '@oro_shopping_list.manager.shopping_list_total'
        tags:
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.post_load, method: onPostLoad }
