layout:
    imports:
        - oro_product_grid

        -
            id: oro_product_grid_sidebar_filters
            root: page_sidebar
            namespace: product

    actions:
        - '@setBlockTheme':
            themes: 'OroProductBundle:layouts:blank/oro_product_frontend_product_search/product_search.html.twig'

        - '@add':
            id: search_title
            parentId: page_main_header
            blockType: text

        - '@setOption':
            id: product_datagrid
            optionName: grid_name
            optionValue: frontend-product-search-grid

        - '@setOption':
            id: product_datagrid
            optionName: current_row_view
            optionValue: '=data["oro_product_datagrid_row_view"].getThemeByGridName("frontend-product-search-grid")'


        - '@setOption':
              id: product_datagrid
              optionName: grid_render_parameters.extra_jsmodules
              optionValue: '=!context["is_mobile"] and data["system_config_provider"].getValue("oro_product.filters_position") === "sidebar" ? ["oroproduct/js/app/datagrid/grid-sidebar-filters-builder"] : []'

        - '@setOption':
              id: product_datagrid
              optionName: grid_render_parameters.enableToggleFilters
              optionValue: '=context["is_mobile"] or data["system_config_provider"].getValue("oro_product.filters_position") !== "sidebar"'


        - '@setOption':
            id: product_datagrid_toolbar_display_options
            optionName: current_row_view
            optionValue: '=data["oro_product_datagrid_row_view"].getThemeByGridName("frontend-product-search-grid")'

        - '@setOption':
            id: product_datagrid_row_product_sticker_new
            optionName: visible
            optionValue: '=data["oro_product_datagrid_row_view"].getThemeByGridName("frontend-product-search-grid")!="no-image-view"'

        - '@setOption':
            id: product_datagrid_row_product_sticker_new_text
            optionName: visible
            optionValue: '=data["oro_product_datagrid_row_view"].getThemeByGridName("frontend-product-search-grid")=="no-image-view"'

        - '@setOption':
            id: search_title
            optionName: text
            optionValue: '=data["oro_product_search"].getSearchString()'
